CREATE TABLE ASSET_CATEGORY ( 
   ID INT NOT NULL,
   NAME VARCHAR(20),
   DESCRIPTION VARCHAR(50)
);

CREATE TABLE EMPLOYEE ( 
   ID INT NOT NULL,
   FULL_NAME VARCHAR(20),
   DESIGNATION VARCHAR(50) 
);

CREATE TABLE ASSET ( 
   ID INT NOT NULL,
   EMPLOYEE_ID INT,
   CATEGORY_ID INT,
   CONDITION_NOTE VARCHAR(50),
   NAME VARCHAR(50),
   PURCHASE_DATE DATE,
   STATUS VARCHAR(10)
);